### ISSUE TITLE
4th Graph in Feedback Test Crashes with Following Error Code

### ISSUE THREAD

**Issue by spina-a-d** [RUGSoftEng/2017-Cognitive-Sensors#64]
05-15 19:10:48.129 3825-3825/com.teamwan.wander E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.teamwan.wander, PID: 3825
                                                                  java.lang.ClassCastException: com.github.mikephil.charting.data.BarData cannot be cast to com.github.mikephil.charting.data.LineData
                                                                      at com.github.mikephil.charting.charts.LineChart.getLineData(LineChart.java:47)
                                                                      at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:88)
                                                                      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:247)
                                                                      at android.view.View.draw(View.java:17185)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                      at android.view.View.draw(View.java:16951)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                      at android.view.View.draw(View.java:17188)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                      at android.view.View.draw(View.java:16951)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                      at android.view.View.draw(View.java:17188)
                                                                      at android.support.v4.view.ViewPager.draw(ViewPager.java:2443)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                      at android.view.View.draw(View.java:16951)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jakedavison** [comment]
This is fixed now.
